netlify/framework-info

- CONTRIBUTING.md
This PR fixes a type with the contributing guide
> fix(contributing): use correct repo name

- src/frameworks/docusaurus.json
See https://github.com/netlify/cli/blob/a1b435febb54d596774e75c8fdf18b8cee6d5791/src/detectors/docusaurus.js#L38
> fix(docusaurus): add missing BROWSER env variable

- src/frameworks/quasar-v0.17.json
See https://v0-17.quasar-framework.org/guide/quasar-cli.html#dev-Development-Server and https://github.com/netlify/cli/blob/a1b435febb54d596774e75c8fdf18b8cee6d5791/src/detectors/quasar-v0.17.js#L9
> feat: add quasar-v0.17

- package.json
> chore: fix version script

- package.json
Follow up on https://github.com/netlify/framework-info/pull/62
> chore: remove redundant scripts

- .eslintrc.js
- .github/workflows/workflow.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
- site/react/App.jsx
- site/react/index.jsx
- site/vanilla/index.html
This PR enforces JSX and HTML files linting using a shared configuration
> chore: improve linting

- src/frameworks/eleventy.json
See https://www.11ty.dev/docs/usage/#re-run-eleventy-when-you-save
> fix(eleventy): update watch command

- src/frameworks/create-react-app.json
Just noticed this one is wrong:
https://create-react-app.dev/docs/getting-started/#npm-run-build-or-yarn-build
> fix(create-react-app): update build directory

- .github/workflows/labeler.yml
Similar to https://github.com/netlify/node-template/pull/20
> chore: use matrix in PR labeler

- package.json
Follow up on https://github.com/netlify/zip-it-and-ship-it/pull/301
> chore: update prepublish script

- src/frameworks/grunt.json
Follow up on https://github.com/netlify/framework-info/pull/111#discussion_r563790756
> fix: remove duplicate plugins entry from grunt.json

- src/frameworks/angular.json
This PR updates the build command and directory for Angular.js sites, as per [this Slack thread](https://netlify.slack.com/archives/C012GT6MYKU/p1614183782058100?thread_ts=1614118421.044100&cid=C012GT6MYKU)
> Update the build command and directory for Angular.js

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/fossa.yml
- .github/workflows/release-please.yml
- .github/workflows/workflow.yml
- CONTRIBUTING.md
- README.md
- codecov.yml
- renovate.json5
Following up since I renamed the default branch
> chore: rename master to main

- .github/workflows/release-please.yml
- package.json
This PR fixes the automated release process.
See failure here https://github.com/netlify/framework-info/runs/2121545581?check_suite_focus=true
> chore: fix release process

- src/frameworks/main.js
- src/frameworks/vite.json
This PR adds detection for [Vite](https://vitejs.dev/).
Part of #204.
> feat(frameworks): add Vite

- src/frameworks/blitz.json
- src/frameworks/main.js
Hi! The @blitz-js community would love to see support for Blitz on Netlify. This PR adds framework detection to setup the nextjs build plugin.
> feat: add Blitz.js support

- .github/workflows/workflow.yml
- package.json
- renovate.json5
Fixes https://github.com/netlify/framework-info/issues/251
> chore!: drop support for Node.js 8

- src/frameworks/main.js
- src/frameworks/svelte-kit.json
- src/frameworks/svelte.json
Fixes https://github.com/netlify/framework-info/issues/263
See https://github.com/netlify/cli/pull/2504
> feat: add SvelteKit

- src/frameworks/main.js
- src/frameworks/wmr.json
Adds support for [WMR](https://github.com/preactjs/wmr/)
> feat: add WMR

- renovate.json5
Closes https://github.com/netlify/framework-info/pull/320
> chore(deps): ignore test-each updates for versions >=3

- .github/workflows/pre-release.yml
- CONTRIBUTING.md
This allows using pre-releases like our other repositories.
> chore: allow pre-releases

- .gitignore
- src/frameworks/next-nx.json
- src/frameworks/next.json
Updates plugin settings for Next plugin 4.
> feat: updates for Next plugin 4

- src/frameworks/remix.json
This reverts commit 7ac785eb64b3239ac5858c77f265628551f0e760.
Reverts #788. In the end, the Remix dev command will stay as `remix watch`. For more context, see https://github.com/remix-run/remix/discussions/3753
---
**A picture of a cute animal (not mandatory, but encouraged)**
> chore: Revert "chore: updated Remix dev command (#788)"

- package.json
Forgot to update the rest of these in #828
> fix: update filepaths

- src/frameworks/remix.json
Adds missing framework info for Remix.
Fixes #835 
Relates to https://github.com/remix-run/remix/pull/3104
---
**A picture of a cute animal (not mandatory, but encouraged)**
> fix: updated Remix framework info that was missing
