- src/main.js
Switched to `typedef` to avoid duplication and fixes a bug with the definitions of options.
> fix(jsdoc): use typedef instead of dot notation

- src/frameworks/main.js
- test/frameworks.js
This adds missing frameworks to `main.js` and adds a test to verify there are no missing ones
> fix: add missing frameworks to main.js

- .github/workflows/release-please.yml
- CONTRIBUTING.md
This changes our publishing flow to use release PRs.
See example:
https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/pull/102
https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/releases/tag/v1.0.11
We can port it to other repos if it works well.
> npm publishing part is still done locally
> chore: use release-please action

- package.json
We can remove those as they are a part of `eslint-config-node`
> chore: remove unused commit lint deps

- src/frameworks/angular.json
This wrong value originated in our CLI.
I created a new angular project to verify this.
> fix(angular): update watch command

- src/watch.js
- test/fixtures/scripts-order/build-first/package.json
- test/fixtures/scripts-order/dev-first/package.json
- test/fixtures/scripts-order/postfix-format/package.json
- test/run_script.js
- test/watch.js
Related to https://github.com/netlify/cli/issues/1252#issuecomment-708618270 and I also noticed this impacts the `svelte` detector.
We should return the same result if script order is different.
We should also find a way to sort https://github.com/netlify/framework-info/blob/26a3b71c04d02c0a1d1baa3dbbc69745adc6683d/src/watch.js#L27 but I'm not sure how to do it (yet).
> fix(watch-command): return watch commands in consistent order

- .github/workflows/release-please.yml
This is required for `create-release` PRs to have status checks. See https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
> chore(ci): use personal access token for releases

- src/dev.js
- test/dev.js
- test/fixtures/scripts-order/command-substring/package.json
Related to https://github.com/netlify/cli/issues/1252
We need to sort the scripts when we match a preferred command
> fix: sort preferred scripts

- .github/workflows/workflow.yml
Switch to `npm ci` and remove a redundant env variable
> ci: use npm ci instead of install

- package.json
npm 7 changed the way globbing patterns are interpreted in `files` in `package.json`. This is undocumented, so I'm not sure whether this is a bug or not. This results in all `*~` files (Vim temporary files) to be published to npm, which can double the package size. 
This PR fixes this. I ran `npm pack --dry` before and after to ensure no files were being omitted.
> fix: fix `files` in `package.json`

- renovate.json5
Fixes the renovate config to allow minor/patch updates to ignored packages
> chore: allow non major updates for Node.js 8 packages

- .github/workflows/release-please.yml
See https://github.com/googleapis/release-please#automating-publication-to-npm
I'm going to add an `NPM_TOKEN` as a repo secret.
If this works well we can migrate to other repos.
> chore: automate npm publishing

- renovate.json5
See https://github.com/netlify/framework-info/pull/193
We cannot update `read-pkg-up` until we drop support for Node.js < 12
> chore: add read-pkg-up to renovate ignore list

- .github/workflows/release-please.yml
- .github/workflows/workflow.yml
Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.
> chore: run CI on latest Node.js

- src/frameworks/main.js
- src/frameworks/redwoodjs.json
We on the RedwoodJS Core Team https://redwoodjs.com noticed that that there is no Redwood common config here: https://docs.netlify.com/configure-builds/common-configurations/
And we found out that this framework detection library "helps with build settings heuristics when creating new sites or running netlify dev, and also to track usage of different tools across the [Netlify] platform". That influences things like which "common configurations" get add to the docs.
So, this PR adds framework detection for RedwoodJS so that all the above can happen.
The key way to detect is the presence of the `redwood.toml` file.
```js
"detect": {
"configFiles": [
"redwood.toml"
]
},
```
Thanks!
> feat: Add framework detection support for RedwoodJS

- renovate.json5
Handles https://github.com/netlify/framework-info/pull/271.
Sets the allowed versions to the latests supporting Node.js 10
> chore(deps): configure renovate for Node.js 10 packages

- src/frameworks/jekyll.json
Related to https://github.com/netlify/framework-info/issues/205 and https://github.com/netlify/cli/pull/2312
Adds missing Jekyll configuration files
> fix(jekyll): add additional config files

- src/frameworks/main.js
- src/frameworks/next-nx.json
- src/frameworks/next.json
When building Next.js sites via Nx we need to use different commands and ports. See https://ntl.fyi/nx-next for docs. 
We detect `@nrwl/next` rather than `nx` because we don't want to catch other uses of Nx, e.g. Angular.
> feat: add detection of Next with Nx

- src/frameworks/vite.json
Follow up on https://github.com/netlify/cli/pull/2883
This will be required once https://github.com/netlify/cli/pull/1704 lands, see https://github.com/netlify/cli/pull/1704/files#diff-42c491dfbe209d7493ec82cd5d031be64f17cf6e622201768d29b3539194d9e1R83 vs https://github.com/netlify/cli/blob/88df4e09704567377f96035480793f602d067636/src/commands/dev/index.js#L88
> fix(framework-vite): remove HTTP polling

- src/dev.js
- test/dev.js
- test/fixtures/scripts-order/vite-framework/package.json
Related to https://github.com/netlify/cli/pull/1704
Fixes detection for the `vite` framework where we return `npm run serve` as the first possible command instead of `npm run dev`.
Since the `vite` dev command doesn't have any arguments the detection matches all possible scripts.
We solve this by sorting the scripts based on priority.
> At the moment the CLI detection logic returns the first script as shown in `package.json` which is confusing as the script order in `package.json` impacts the https://github.com/netlify/cli/issues/1252
> fix(dev-detection): prioritize dev over serve

- src/dev.js
- test/dev.js
- test/fixtures/excluded_script/package.json
Fixes https://github.com/netlify/cli/issues/3045
Reinstates the CLI logic that filters out `netlify dev` as a dev script.
I planned to do it in the CLI as a part of https://github.com/netlify/cli/pull/1704, but forgot.
After giving it some though I think it makes sense to have it in `framework-info` as there are others scripts we might want to exclude.
> fix(dev): add list of excluded dev commands

- src/frameworks/gatsby.json
Adds the env var `GATSBY_PRECOMPILE_DEVELOP_FUNCTIONS=true`, so that `ntl dev` can load functions directly rather than proxying
> feat(gatsby): precompile functions in develop

- src/frameworks/svelte-kit.json
I don't know why it says `static`. That's an input directory where static assets are located and we shouldn't put output there
> fix(sveltekit): specify better output location

- .github/workflows/pre-release.yml
This repository requires the `prepublishOnly` script to build assets before `npm publish`.
> fix: remove `--ignore-scripts` from `npm publish` in prereleases

- src/frameworks/main.js
- src/frameworks/remix.json
- test/frameworks.js
This starts the process of adding Remix to framework detection. There are a few open questions that I think I need @netlify/integrations to help with:
1. Right now we have to run both `remix watch` and `netlify dev` together and I'm not sure how to approach that or if it's possible to simplify
2. Remix uses port 8888, which I think is going to cause problems and I'm not sure if there's config available to fix it
I'm happy to close this PR if you've already got one rolling. If not, I figured I'd try to get the ball rolling as much as possible so we can get seamless Remix support in place.
Thanks!
> feat!: add Remix, make dev port optional

- src/frameworks/remix.json
I believe https://github.com/netlify/framework-info/pull/658 had a typo.
In my Remix project the config is a `.js` file and trying to switch to `.mjs` didn't work (that is changing the extension and using ES modules).
> fix(remix): use correct configuration file

- .github/workflows/workflow.yml
- package-lock.json
- package.json
See https://github.com/netlify/js-client/pull/659
This fixes how we use Husky with its latest version.
---
> chore: fix Husky

- cypress/run.js
Part of https://github.com/netlify/framework-info/issues/714
This disables the Cypress tests on Firefox until we figure out why they are failing.
---
> chore: disable tests on Firefox

- src/frameworks/remix.json
Updates the Remix dev command to `remix dev`. When the command was initially added, `remix dev` did not exist.
Closes #787 
---
**A picture of a cute animal (not mandatory, but encouraged)**
> chore: updated Remix dev command

- src/frameworks/vite.json
There was a typo in the excluded npm dependencies for the vite framework information, causing multiple frameworks to be returned fort Qwik. The typo has been fixed.
Now instead of 
```
❯ ntl dev
Debugger attached.
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
? Multiple possible start commands found (Use arrow keys or type to search)
❯ [Qwik] 'npm run build.client' 
[Qwik] 'npm run build.ssr' 
[Qwik] 'npm run dev.client' 
[Qwik] 'npm run dev.debug' 
[Qwik] 'npm run dev.ssr' 
[Vite] 'npm run build.client' 
[Vite] 'npm run build.ssr' 
(Move up and down to reveal more choices)
```
when you run `ntl dev`, you'll get the following because only one framework is found.
```
◈ Starting Netlify Dev with Qwik
> build.client
> …
```
> fix: fixed typo in qwik excluded dependency

- src/frameworks/svelte-kit.json
- src/frameworks/vite.json
Updates the framework info for SvelteKit. I confirmed these changes with Brittney.
Fixes #817
---
**A picture of a cute animal (not mandatory, but encouraged)**
> chore: updated SvelteKit framework info

- package.json
Fixes #827 
This was an entry that I forgot to update when migrating from webpack to vite in #819 .
> fix: update the files entry in package.json
